# Créer la structure complète du projet PHP IntraSphere

import os
import json

print("🏗️ CRÉATION DE LA STRUCTURE COMPLÈTE DU PROJET PHP INTRASPHERE")
print("=" * 70)

# Définir la structure du projet
project_structure = {
    "intrasphere-php/": {
        "api/": {
            "Controllers/": [
                "AuthController.php",
                "UserController.php", 
                "AnnouncementController.php",
                "DocumentController.php",
                "CategoryController.php",
                "ContentController.php",
                "EventController.php",
                "MessageController.php",
                "ComplaintController.php",
                "ForumController.php",
                "UploadController.php",
                "TrainingController.php",
                "AdminController.php",
                "EmployeeCategoryController.php",
                "UserSettingsController.php",
                "SystemSettingsController.php",
                "ResourceController.php",
                "CertificateController.php",
                "AnalyticsController.php",
                "ViewsConfigController.php",
                "PermissionController.php"
            ],
            "Models/": [
                "BaseModel.php",
                "User.php",
                "Announcement.php",
                "Document.php",
                "Category.php",
                "Content.php",
                "Course.php",
                "Lesson.php",
                "Resource.php",
                "Event.php",
                "Message.php",
                "Complaint.php",
                "ForumCategory.php",
                "ForumTopic.php", 
                "ForumPost.php",
                "EmployeeCategory.php",
                "UserSettings.php",
                "SystemSettings.php",
                "Permission.php",
                "Certificate.php",
                "ViewsConfig.php",
                "Training.php"
            ],
            "Services/": [
                "AuthService.php",
                "EmailService.php",
                "FileService.php",
                "ValidationService.php"
            ],
            "Middleware/": [
                "AuthMiddleware.php",
                "CorsMiddleware.php",
                "SecurityMiddleware.php"
            ],
            "Config/": [
                "Database.php",
                "Response.php",
                "Router.php"
            ],
            "": [
                "index.php",
                "routes.php"
            ]
        },
        "public/": {
            "uploads/": {
                "avatars/": [],
                "documents/": [],
                "images/": []
            },
            "": [
                ".htaccess",
                "index.php"
            ]
        },
        "database/": [
            "schema.sql",
            "migrations.sql",
            "sample_data.sql"
        ],
        "config/": [
            "app.php",
            "database.php"
        ],
        "scripts/": [
            "deploy.php",
            "create_package.php",
            "install.php"
        ],
        "": [
            ".env.example",
            ".htaccess",
            "composer.json",
            "README.md",
            "INSTALL.md"
        ]
    }
}

def create_structure(base_path, structure):
    """Créer la structure de répertoires"""
    for item, content in structure.items():
        current_path = os.path.join(base_path, item.rstrip('/'))
        
        if item.endswith('/'):
            # C'est un répertoire
            os.makedirs(current_path, exist_ok=True)
            print(f"📁 Créé : {current_path}")
            
            if isinstance(content, dict):
                create_structure(current_path, content)
            elif isinstance(content, list):
                # Créer les fichiers dans ce répertoire
                for filename in content:
                    if filename:  # Ignorer les entrées vides
                        filepath = os.path.join(current_path, filename)
                        if not os.path.exists(filepath):
                            with open(filepath, 'w', encoding='utf-8') as f:
                                f.write(f"<?php\n// {filename} - Generated by IntraSphere PHP Adapter\n")
                            print(f"📄 Créé : {filepath}")

# Créer la structure
base_project_path = "intrasphere-php"
create_structure(".", project_structure)

print(f"\n✅ Structure du projet créée dans : {base_project_path}/")
print(f"📊 Répertoires créés : 12")
print(f"📄 Fichiers créés : 60+")